name       : haskell-uniplate
version    : 1.6.12
release    : 2
source     :
    - http://hackage.haskell.org/package/uniplate-1.6.12/uniplate-1.6.12.tar.gz : fcc60bc6b3f6e925f611646db90e6db9f05286a9363405f844df1dc15572a8b7
license    : BSD-3-Clause
component  : programming.haskell
summary    : Uniplate is library for writing simple and concise generic operations.
description: |
    Uniplate is library for writing simple and concise generic operations. Uniplate has similar goals to the original Scrap Your Boilerplate work, but is substantially simpler and faster.
builddeps  :
    - haskell-cabal-install
    - haskell-syb
    - haskell-unordered-containers
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
